name: selfdriving
channels:
- menpo
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py35_0
- asn1crypto=0.22.0=py35_0
- backports=1.0=py35_1
- backports.functools_lru_cache=1.4=py35_1
- blas=1.1=openblas
- bleach=2.0.0=py35_0
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py35_0
- cffi=1.10.0=py35_0
- click=6.7=py35_0
- cryptography=2.0.3=py35_0
- cycler=0.10.0=py35_0
- dask-core=0.15.3=py_0
- decorator=4.1.2=py35_0
- entrypoints=0.2.3=py35_1
- eventlet=0.21.0=py35_0
- ffmpeg=3.4.1=0
- flask=0.12.2=py35_0
- flask-socketio=2.9.2=py35_0
- freetype=2.7=1
- greenlet=0.4.12=py35_0
- h5py=2.7.1=py35_1
- hdf5=1.8.18=2
- html5lib=0.999999999=py35_0
- idna=2.6=py35_1
- imageio=2.1.2=py35_0
- ipykernel=4.6.1=py35_0
- ipython=6.2.1=py35_0
- ipython_genutils=0.2.0=py35_0
- itsdangerous=0.24=py_2
- jedi=0.10.2=py35_0
- jinja2=2.9.6=py35_0
- jpeg=9b=1
- jsonschema=2.6.0=py35_0
- jupyter=1.0.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_console=5.1.0=py35_0
- jupyter_core=4.3.0=py35_0
- libffi=3.2.1=3
- libgfortran=3.0.0=0
- libiconv=1.15=0
- libpng=1.6.34=0
- libsodium=1.0.10=0
- libtiff=4.0.9=0
- markupsafe=1.0=py35_0
- matplotlib=2.1.0=py35_0
- mistune=0.7.4=py35_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py35_0
- ncurses=5.9=10
- networkx=2.0=py35_0
- notebook=5.1.0=py35_0
- numpy=1.13.3=py35_blas_openblas_200
- olefile=0.44=py35_0
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pandas=0.20.3=py35_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py35_0
- patsy=0.4.1=py35_0
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.2.1=py35_0
- pip=9.0.1=py35_0
- prompt_toolkit=1.0.15=py35_0
- ptyprocess=0.5.2=py35_0
- pycparser=2.18=py35_0
- pygments=2.2.0=py35_0
- pyopenssl=17.2.0=py35_0
- pyparsing=2.2.0=py35_0
- python=3.5.2=5
- python-dateutil=2.6.1=py35_0
- python-engineio=1.7.0=py35_0
- python-socketio=1.8.1=py_0
- pytz=2017.2=py35_0
- pywavelets=0.5.2=np113py35_0
- pyzmq=16.0.2=py35_2
- qtconsole=4.3.1=py35_0
- readline=6.2=0
- scikit-image=0.13.0=py35_2
- scikit-learn=0.19.0=py35_blas_openblas_201
- scipy=0.19.1=py35_blas_openblas_202
- seaborn=0.8.1=py35_0
- setuptools=36.3.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_1
- six=1.11.0=py35_1
- sqlite=3.13.0=1
- statsmodels=0.8.0=py35_0
- terminado=0.6=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.19=2
- toolz=0.8.2=py_2
- tornado=4.5.2=py35_0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- werkzeug=0.12.2=py_1
- wheel=0.30.0=py_1
- x264=20131217=3
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- qt=4.8.7=4
- ipywidgets=5.1.5=py35_0
- opencv3=3.1.0=py35_0
- pyqt=4.11.4=py35_2
- tbb=4.3_20141023=0
- widgetsnbextension=1.2.3=py35_1
- pip:
  - backports.functools-lru-cache==1.4
  - dask==0.15.3
  - docopt==0.6.2
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - keras==1.2.1
  - moviepy==0.2.3.2
  - prompt-toolkit==1.0.15
  - protobuf==3.4.0
  - pyyaml==3.12
  - tensorflow==0.12.1
  - theano==0.9.0
  - tqdm==4.11.2
